# Generated by Django 4.2.5 on 2023-09-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0002_alter_spotifytoken_refresh_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spotifytoken",
            name="expires_in",
            field=models.DateTimeField(),
        ),
    ]
